version: "2"
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    networks: 
      - webnet
    volumes:
      - /mnt/jenkins_home:/var/jenkins_home
networks: 
   webnet: